### ISSUE TITLE
github stats are not getting updated in production

### ISSUE THREAD

**Issue by domicode** [panter/dashboard.panter.ch#16]
all the guthub stats show 0 in production. If I run it locally I get the correct numbers which are not 0. Also the last update is at 3am whereas it's scheduled to do it every 1 minute.

**Comment by koffeinfrei** [comment]
Yes the problem is because the in-process scheduler that is used by dashing, which doesn't work with multi-process servers like unicorn. Markus and I are already looking into it (there are some workaround to make it work with unicorn, or just use a single-process server like thin).

(This issue is the reason why I haven't announced the production deployment yet :smirk:)

**Comment by koffeinfrei** [comment]
Solved by @toupeira: Unicorn is limited to 1 worker process for now.
